dev_contest_api:
    resource: "@DevContestApiBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

#fos_oauth_server_token:
#    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
#
#fos_oauth_server_authorize:
#    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

#acme_oauth_server_auth_login:
#    pattern:  /oauth/v2/auth_login
#    defaults: { _controller: AcmeDemoBundle:Security:login }
#
#acme_oauth_server_auth_login_check:
#    pattern:  /oauth/v2/auth_login_check
#    defaults: { _controller: AcmeDemoBundle:Security:loginCheck }

#devcontest_index:
#    pattern:  /
#    defaults: { _controller: DevContestApiBundle:Security:index }
#
#devcontest_login:
#    pattern:  /login_user
#    defaults: { _controller: DevContestApiBundle:Security:login }
#
#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect
#
#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /login
#
#github_login:
#    path: /login/check-github
#
#bitbucket_login:
#    path: /login/check-bitbucket