security:
    encoders:
        DevContest\DevContestApiBundle\Entity\User:
            algorithm:            pbkdf2
            hash_algorithm:       sha512
            encode_as_base64:     true
            iterations:           1000
            key_length:           40

    role_hierarchy:
        ROLE_API:         [ROLE_USER, ROLE_OWNER]
        ROLE_ADMIN:       [ROLE_API, ROLE_ALLOWED_TO_SWITCH]

    providers:
        a0:
            id: dev_contest.api.security.a0_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            stateless:  true
            simple_preauth:
                authenticator: jwt_auth.jwt_authenticator

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
