
# SMTP trap
basemailhog:
    image: mailhog/mailhog
    labels:
        - "com.devcontest.project=dev-contest-api"

baseengine:
    image: bflaceliere/php7-fpm-symfony
    volumes:
        - "..:/home/docker:rw"
        - "../docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    user: "1000:1000"
    working_dir: "/home/docker"
    labels:
      - "com.devcontest.project=dev-contest-api"

basefront:
    image: nginx
    volumes:
        - "..:/home/docker:ro"
        - "../docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"
    labels:
         - "com.project=dev-contest-api"

basepostgres:
    image: postgres
    environment:
        - POSTGRES_USER=devcontest
        - POSTGRES_PASSWORD=devcontest
        - PGPASSWORD=devcontest
    labels:
        - "com.devcontest.project=dev-contest-api"

basedatapostgres:
    image: tianon/true
    volumes:
        - /var/lib/postgresql/data
    labels:
          - "com.devcontest.project=dev-contest-api"
