Knp\Bundle\PaginatorBundle\Pagination\SlidingPagination:
    exclusion_policy: ALL
    virtual_properties:
        getPageCount:
            type: integer
            serialized_name:
                total_pages
            groups: [all, list]