services:
  dev_contest.api.doctrine.dev_contest_naming_strategy:
    class: DevContest\DevContestApiBundle\Doctrine\DevContestNamingStrategy
    arguments: []
  dev_contest.api.repository.user:
    class: DevContest\DevContestApiBundle\Repository\UserRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments: ['DevContestApiBundle:User']
  dev_contest.api.user_provider:
    class: DevContest\DevContestApiBundle\Provider\UserProvider
    arguments: [@dev_contest.api.repository.user]
#    dev_contest_api.example:
#        class: DevContest\DevContestApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
