<?php

namespace DevContest\DevContestApiBundle\Repository;

/**
 * ContestTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestTestRepository extends AbstractEntityRepository
{
}
