<?php

namespace DevContest\DevContestApiBundle\Repository;

/**
 * ContestStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestStepRepository extends AbstractEntityRepository
{
    /**
     * Get findAll query builder
     *
     * @param integer $contestId
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function qFindByContestId(int $contestId)
    {
        return $this->createQueryBuilder('u')
                    ->where('u.contest = :contestId')
                    ->setParameter('contestId', $contestId);
    }
}
