<?php

namespace DevContest\DevContestApiBundle\Repository;

/**
 * ContestStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestStepRepository extends AbstractEntityRepository
{
}
