<?php

namespace DevContest\DevContestApiBundle\Repository;

/**
 * UserContestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserContestRepository extends \Doctrine\ORM\EntityRepository
{
}
